//! Gauss–Legendre quadrature rules on `[−1, 1]`, generated by Newton
//! iteration on `P_n` so the crate carries no tabulated constants.

/// Nodes and weights of the `n`-point Gauss–Legendre rule.
pub fn gauss_legendre(n: usize) -> (Vec<f64>, Vec<f64>) {
    let mut nodes = vec![0.0; n];
    let mut weights = vec![0.0; n];
    let nf = n as f64;
    for i in 0..n {
        let mut x = (std::f64::consts::PI * (i as f64 + 0.75) / (nf + 0.5)).cos();
        let mut dp = 1.0;
        for _ in 0..100 {
            let (p, d) = legendre_with_derivative(n, x);
            dp = d;
            let dx = p / d;
            x -= dx;
            if dx.abs() < 1e-16 {
                break;
            }
        }
        nodes[i] = -x;
        weights[i] = 2.0 / ((1.0 - x * x) * dp * dp);
    }
    (nodes, weights)
}

/// 32-point rule as fixed arrays (used by the stiffness integrals).
pub fn gauss_legendre_32() -> ([f64; 32], [f64; 32]) {
    let (n, w) = gauss_legendre(32);
    let mut nodes = [0.0; 32];
    let mut weights = [0.0; 32];
    nodes.copy_from_slice(&n);
    weights.copy_from_slice(&w);
    (nodes, weights)
}

fn legendre_with_derivative(n: usize, x: f64) -> (f64, f64) {
    let mut p0 = 1.0;
    let mut p1 = x;
    for k in 2..=n {
        let kf = k as f64;
        let p2 = ((2.0 * kf - 1.0) * x * p1 - (kf - 1.0) * p0) / kf;
        p0 = p1;
        p1 = p2;
    }
    let nf = n as f64;
    let dp = nf * (x * p1 - p0) / (x * x - 1.0);
    (p1, dp)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn integrates_polynomials_exactly() {
        let (x, w) = gauss_legendre(8);
        let sum: f64 = w.iter().sum();
        assert!((sum - 2.0).abs() < 1e-14);
        let m14: f64 = x.iter().zip(&w).map(|(x, w)| w * x.powi(14)).sum();
        assert!((m14 - 2.0 / 15.0).abs() < 1e-14, "{m14}");
    }
}
